In [1]:
import numpy as np

In [2]:
a = np.array([(2,3,4,8,7,5,7),(6,7,8,9,5,3,2)])

In [3]:
a

array([[2, 3, 4, 8, 7, 5, 7],
       [6, 7, 8, 9, 5, 3, 2]])

In [19]:
a =a.reshape(2,7)

In [5]:
a

array([[2, 3],
       [4, 8],
       [7, 5],
       [7, 6],
       [7, 8],
       [9, 5],
       [3, 2]])

In [6]:
print(a.sum())

76


In [7]:
print(a.max())

9


In [8]:
a.min()

2

In [10]:
print(np.vstack(a))

[[2 3]
 [4 8]
 [7 5]
 [7 6]
 [7 8]
 [9 5]
 [3 2]]


In [12]:
print(np.hstack(a))

[2 3 4 8 7 5 7 6 7 8 9 5 3 2]


In [16]:
a.std()

2.2587697572631282

In [15]:
a.ravel()

array([2, 3, 4, 8, 7, 5, 7, 6, 7, 8, 9, 5, 3, 2])